
project_id = "piavblsenfvaqomnbimo"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "auth", "extensions"]
extra_search_path = ["public", "storage", "auth", "extensions"]

[db]
port = 54322
shadow_port = 54320
major_version = 15

[functions.ai-content-generation]
verify_jwt = true

